FROM cassandra:3.0.4
COPY keyspace_def.txt /usr/src/keyspace_def.txt
COPY master.sh /usr/src/master.sh
COPY deregister.sh /usr/src/deregister.sh
COPY node.sh /usr/src/node.sh
COPY currentnodes.sh /usr/src/currentnodes.sh
